name: Build package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pkgbuild:
    name: Build & Publish PKGBUILD
    runs-on: ubuntu-latest
    steps:
      - name: Build Package
        uses: ouuan/pkgbuild-action@master
        id: build-package
        with:
          path: rog-ally-motion-evdev
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rog-ally-motion-evdev-${{ github.run_id }}
          path: ${{ steps.build-package.outputs.pkgfile }}